import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    fontSize: 14,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  } satisfies CSSProperties,
  body: {
    color: "var(--text-secondary)",
    lineHeight: 1.6,
    marginBottom: 12,
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase" as const,
    color: "var(--text-tertiary)",
    marginBottom: 6,
    marginTop: 12,
  } satisfies CSSProperties,
  riskLevelRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  } satisfies CSSProperties,
  badge: {
    display: "inline-block",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  } satisfies CSSProperties,
  badgeLow: {
    background: "var(--ok-bg, #052e1c)",
    color: "var(--ok, #3dd68c)",
    border: "1px solid var(--ok, #3dd68c)",
  } satisfies CSSProperties,
  badgeMedium: {
    background: "var(--warn-bg, #2e1c05)",
    color: "var(--warn, #f5a623)",
    border: "1px solid var(--warn, #f5a623)",
  } satisfies CSSProperties,
  badgeHigh: {
    background: "var(--crit-bg, #2e0a0a)",
    color: "var(--crit, #f87171)",
    border: "1px solid var(--crit, #f87171)",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    margin: 0,
    padding: 0,
    listStyle: "none",
  } satisfies CSSProperties as CSSProperties,
  listItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    color: "var(--text-secondary)",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  bullet: {
    flexShrink: 0,
    marginTop: 2,
    color: "var(--text-tertiary)",
  } satisfies CSSProperties,
  riskCard: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "10px 12px",
    marginBottom: 8,
    background: "var(--bg-base)",
  } satisfies CSSProperties,
  riskHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 4,
  } satisfies CSSProperties,
  riskTitle: {
    fontWeight: 600,
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  riskExplanation: {
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    marginBottom: 8,
    fontSize: 13,
  } satisfies CSSProperties,
  fileRef: {
    display: "inline-block",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11,
    color: "var(--accent, #60a5fa)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 3,
    padding: "1px 5px",
    marginRight: 4,
    marginBottom: 2,
    textDecoration: "none",
    cursor: "pointer",
  } satisfies CSSProperties,
  footer: {
    marginTop: 14,
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
    display: "flex",
    justifyContent: "flex-end",
  } satisfies CSSProperties,
  actionBtn: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    color: "var(--text-secondary)",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  generateBtn: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 13,
    color: "var(--text-secondary)",
    background: "var(--bg-elevated)",
    cursor: "pointer",
    display: "block",
    width: "100%",
    textAlign: "center" as const,
  } satisfies CSSProperties,
  degradedBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 13,
    lineHeight: 1.4,
  } satisfies CSSProperties,
} as const;
